Create table CurrentOpenPeriod (
    OpenPeriodId BIGINT PRIMARY KEY,
    OpenPeriodName VARCHAR(255),
    OpenPeriodStartDate DATE,
    OpenPeriodEndDate DATE,
    OpenPeriodStatus VARCHAR(255),
    OpenPeriodCreatedAt DATETIME,
    OpenPeriodUpdatedAt DATETIME,
    OrganizationId BIGINT,
    BookId BIGINT
);

create table Calendar (
    PeriodId BIGINT PRIMARY KEY,
    PeriodName VARCHAR(255),
    QuarterStartDate DATE,
    QuarterEndDate DATE,
    MonthStartDate DATE,
    MonthEndDate DATE,
    YearStartDate DATE,
    YearEndDate DATE,
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);

create table Currency (
    Id BIGINT PRIMARY KEY,
    CurrencyName VARCHAR(255),
    CurrencyCode VARCHAR(255),
    CurrencyRounding BIGINT, 
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);

create table PerformanceObligationTemplate(
    Id BIGINT PRIMARY KEY,
    Name VARCHAR(255),
    Description VARCHAR(255),
    RevenueReleaseMethod VARCHAR(255),
    RevenueReleaseTiming VARCHAR(255),
    RevenueCalculationMethod VARCHAR(255),
    IsDistinctPob BOOLEAN,
    IsActive BOOLEAN,
    createdPeriodId BIGINT,
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);

create table PerformanceObligationRule(
    Id BIGINT PRIMARY KEY,
    Name VARCHAR(255),
    Description VARCHAR(255),
    PerformanceObligationTemplateId BIGINT,
    IsActive BOOLEAN,
    createdPeriodId BIGINT,
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);

create table PerformanceObligationRuleFilter(
    Id BIGINT PRIMARY KEY,
    PerformanceObligationRuleId BIGINT,
    FilterFieldName VARCHAR(255),
    FilterOperator VARCHAR(255),
    FilterValue VARCHAR(255),
    IsActive BOOLEAN,
    createdPeriodId BIGINT,
    CreatedAt DATETIME,
    UpdatedAt DATETIME,
    CreatedBy VARCHAR(255),
    UpdatedBy VARCHAR(255)
);

create table RevenueContractGroupingTemplate (
    Id BIGINT PRIMARY KEY,
    Name VARCHAR(255),
    Description VARCHAR(255),
    IsActive BOOLEAN,
    createdPeriodId BIGINT,
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);

create table RevenueContractGroupingHierarchy (
    Id BIGINT PRIMARY KEY,
    sequence BIGINT,
    RevenueContractGroupingTemplateId BIGINT,
    GroupingFields VARCHAR(255),
    createdPeriodId BIGINT,
    IsActive BOOLEAN,
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);

create table RevenueContractGroupingFilter(
    Id BIGINT PRIMARY KEY,
    RevenueContractGroupingTemplateId BIGINT,
    FilterFieldName VARCHAR(255),
    FilterOperator VARCHAR(255),
    FilterValue VARCHAR(255),
    IsActive BOOLEAN,
    createdPeriodId BIGINT,
    CreatedAt DATETIME,
    UpdatedAt DATETIME,
    CreatedBy VARCHAR(255),
    UpdatedBy VARCHAR(255)
);

create table StandaloneSellPriceHierarchy (
    seq BIGINT PRIMARY KEY,
    StandaloneSellPriceTemplateId BIGINT,
    StandaloneSellPriceTemplateName VARCHAR(255),
    RevenueContractGroupingTemplateId BIGINT,
    IsActive BOOLEAN,
    createdPeriodId BIGINT,
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);

create table StandaloneSellPriceTemplate (
    Id BIGINT PRIMARY KEY,
    Name VARCHAR(255),
    Description VARCHAR(255),
    stratificationFields VARCHAR(255),
    ApplyFieldName VARCHAR(255),
    createdPeriodId BIGINT,
    IsActive BOOLEAN,
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);

create table StandaloneSellPriceBatchHeader (
    Id BIGINT PRIMARY KEY,
    StandaloneSellPriceTemplateId BIGINT,
    Name VARCHAR(255),
    Description VARCHAR(255),
    SspType VARCHAR(255),
    EffectiveFromDate DATE,
    EffectiveToDate DATE,
    Status VARCHAR(255),
    createdPeriodId BIGINT,
    CreatedBy VARCHAR(255),
    CreatedAt DATETIME,
    UpdatedBy VARCHAR(255),
    UpdatedAt DATETIME,
    IsActive BOOLEAN
);

create table StandaloneSellPriceBatchDetails (
    Id BIGINT PRIMARY KEY,
    BatchId BIGINT,
    StandaloneSellPriceTemplateId BIGINT,
    attributeField1 VARCHAR(255),
    attributeField2 VARCHAR(255),
    attributeField3 VARCHAR(255),
    attributeField4 VARCHAR(255),
    attributeField5 VARCHAR(255),
    attributeField6 VARCHAR(255),
    attributeField7 VARCHAR(255),
    attributeField8 VARCHAR(255),
    attributeField9 VARCHAR(255),
    attributeField10 VARCHAR(255),
    aboveSspPercentage NUMERIC(18, 2),
    sspPercentage NUMERIC(18, 2),
    belowSspPercentage NUMERIC(18, 2),
    aboveSspPrice DECIMAL(65, 27),
    sspPrice DECIMAL(65, 27),
    belowSspPrice DECIMAL(65, 27),
    IsActive BOOLEAN,
    createdPeriodId BIGINT,
    CreatedAt DATETIME,
    UpdatedAt DATETIME,
    CreatedBy VARCHAR(255),
    UpdatedBy VARCHAR(255)
);

create table revenueContractBatchHeader(
    BatchId BIGINT PRIMARY KEY,
    Name VARCHAR(255),
    Description VARCHAR(255),
    RevenueContractGroupingTemplateId BIGINT,
    Status VARCHAR(255),
    StageRecordProcessed BIGINT,
    revenueContractRecordProcessed BIGINT,
    createdPeriodId BIGINT,
    CreatedBy VARCHAR(255),
    CreatedAt DATETIME,
    UpdatedBy VARCHAR(255),
    UpdatedAt DATETIME
);

create table revenueContractBatchDetails(
    Id BIGINT PRIMARY KEY,
    BatchId BIGINT,
    RevenueContractId BIGINT,
    StageRecordProcessed BIGINT,
    revenueContractRecordProcessed BIGINT,
    processedFlag BOOLEAN,
    createdPeriodId BIGINT,
    CreatedBy VARCHAR(255),
    CreatedAt DATETIME,
    UpdatedBy VARCHAR(255),
    UpdatedAt DATETIME
);

create table revenueContractGroupDetails(
    Id BIGINT PRIMARY KEY, 
    RevenueContractId BIGINT,
    GroupingValue VARCHAR(255),
    ClosedFlag VARCHAR(1),
    createdPeriodId BIGINT,
    IsActive BOOLEAN,
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);

create table revenueContractReferenceDetails(
    Id BIGINT PRIMARY KEY, 
    RevenueContractId BIGINT,
    salesOrderId VARCHAR(255),
    invoiceId VARCHAR(255),
    createdPeriodId BIGINT,
    IsActive BOOLEAN,
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);

create table revenueContractHeader(
    RevenueContractId BIGINT PRIMARY KEY,
    version BIGINT,
    TotalSellPrice DECIMAL(65, 27),
    TotalListPrice DECIMAL(65, 27),
    TotalCarveAmount DECIMAL(65, 27),
    createdPeriodId BIGINT,
    InitialContractModificationDate DATE,
    ContractModificationDate DATE,
    isRevenueContractPosted BOOLEAN,
    AllocationTreatment VARCHAR(1),
    CreatedBy VARCHAR(255),
    CreatedAt DATETIME,
    UpdatedBy VARCHAR(255),
    UpdatedAt DATETIME,
    IsActive BOOLEAN
);

create table revenueContractPobDetails(
    id BIGINT PRIMARY KEY,
    revenueContractId BIGINT,
    pobTemplateId BIGINT,
    pobRuleId BIGINT,
    Name VARCHAR(255),
    Description VARCHAR(255),
    pobExpiryDate DATE,
    processsedFlag VARCHAR(1),
    IsActive BOOLEAN,
    createdPeriodId BIGINT,
    CreatedAt DATETIME,
    UpdatedAt DATETIME,
    CreatedBy VARCHAR(255),
    UpdatedBy VARCHAR(255)
);

create table revenueContractOrderDetails(
    id BIGINT PRIMARY KEY,
    transactionType VARCHAR(255),
    revenueContractId BIGINT,
    salesOrderId BIGINT,
    salesOrderNumber VARCHAR(255),
    salesOrderDate DATE,
    SellPrice DECIMAL(65, 27),
    ListPrice DECIMAL(65, 27),
    UnitSellPrice DECIMAL(65, 27),
    UnitListPrice DECIMAL(65, 27),
    transactionCurrency VARCHAR(255),
    FunctionalCurrency VARCHAR(255),
    exchangeRate DECIMAL(65, 27),
    globalexchangeRate DECIMAL(65, 27),
    exchangeRateDate DATE,
    customerNumber VARCHAR(255),
    customerName VARCHAR(255),
    itemNumber VARCHAR(255),
    DeferAmount DECIMAL(65, 27),
    RecognizeAmount DECIMAL(65, 27),
    BilledDeferAmount DECIMAL(65, 27),
    BilledRecognizeAmount DECIMAL(65, 27),
    BundleConfigurationId  BIGINT,
    OrderQuantity  DECIMAL(65, 27),
    InvoiceQuantity DECIMAL(65, 27),
    ReturnQuantity DECIMAL(65, 27),
    RevenueStartDate DATE,
    RevenueEndDate DATE,
    Duration BIGINT,
    Term NUMERIC(18, 2),
    BookId BIGINT,
    OrganizationId BIGINT,
    DiscountAmount DECIMAL(65, 27),
    DiscountPercentage DECIMAL(65, 27),
    bundleParentId BIGINT,
    companyCode VARCHAR(255),
    IsCancelOrder BOOLEAN,
    IsReturnOrder BOOLEAN,   
    IsEligibleForAllocation BOOLEAN,
    createdPeriodId BIGINT,
    CumulativeCarveAmount DECIMAL(65, 27),
    CumulativeAllocatedPrice DECIMAL(65, 27),
    Comments VARCHAR(255),
    CreatedBy VARCHAR(255),
    CreatedAt DATETIME,
    UpdatedBy VARCHAR(255),
    UpdatedAt DATETIME, 
    ProductCategory VARCHAR(255),
    ProductClass VARCHAR(255),
    ProductFamily VARCHAR(255),
    ProductLine VARCHAR(255),
    BusinessUnit VARCHAR(255),
    ContractModificationDate DATE,
    SubscriptionId BIGINT,
    SubscriptionName VARCHAR(255),
    SubscriptionVersion BIGINT,
    SubscriptionStartDate DATE,
    SubscriptionEndDate DATE);

create table revenueContractAllocationDetails(
    id BIGINT PRIMARY KEY,
    revenueContractId BIGINT,
    ExtendedSspPrice DECIMAL(65, 27), 
    allocationCurrency VARCHAR(255), 
    exchangeRate DECIMAL(65, 27),
    globalexchangeRate DECIMAL(65, 27),
    exchangeRateDate DATE,
    CarveAmount DECIMAL(65, 27),
    CumulativeReleasedAmount DECIMAL(65, 27),
    CumulativeUnReleasedAmount DECIMAL(65, 27),
    TransactionPrice DECIMAL(65, 27),
    AllocatedPrice DECIMAL(65, 27), 
    NetQuantity  DECIMAL(65, 27),
    Term NUMERIC(18, 2),
    BookId BIGINT,
    OrganizationId BIGINT,
    TransactionFunctionalPrice DECIMAL(65, 27),
    SspTemplateId BIGINT,
    SspId BIGINT,
    sspType VARCHAR(10),
    sspPrice DECIMAL(65, 27),
    sspPercentage DECIMAL(65, 27),
    aboveSspPrice DECIMAL(65, 27),
    belowSspPrice DECIMAL(65, 27),
    belowMidPercentage DECIMAL(65, 27),
    aboveMidPercentage DECIMAL(65, 27), 
    IsCancelOrder BOOLEAN,
    IsReturnOrder BOOLEAN,   
    createdPeriodId BIGINT,
    CumulativeCarveAmount DECIMAL(65, 27),
    CumulativeAllocatedPrice DECIMAL(65, 27),
    Comments VARCHAR(255),
    CreatedBy VARCHAR(255),
    CreatedAt DATETIME,
    UpdatedBy VARCHAR(255),
    UpdatedAt DATETIME);

create table revenueContractOrderAccountDetails(
    id BIGINT PRIMARY KEY,
    revenueContractId BIGINT,
    DeferSegment1 VARCHAR(255),
    DeferSegment2 VARCHAR(255),
    DeferSegment3 VARCHAR(255),
    DeferSegment4 VARCHAR(255),
    DeferSegment5 VARCHAR(255),
    DeferSegment6 VARCHAR(255),
    DeferSegment7 VARCHAR(255),
    DeferSegment8 VARCHAR(255),
    DeferSegment9 VARCHAR(255),
    DeferSegment10 VARCHAR(255),
    RevenueSegment1 VARCHAR(255),
    RevenueSegment2 VARCHAR(255),
    RevenueSegment3 VARCHAR(255),
    RevenueSegment4 VARCHAR(255),
    RevenueSegment5 VARCHAR(255),
    RevenueSegment6 VARCHAR(255),
    RevenueSegment7 VARCHAR(255),
    RevenueSegment8 VARCHAR(255),
    RevenueSegment9 VARCHAR(255),
    RevenueSegment10 VARCHAR(255),
    customSegment1 VARCHAR(255),
    customSegment2 VARCHAR(255),
    customSegment3 VARCHAR(255),
    customSegment4 VARCHAR(255),
    customSegment5 VARCHAR(255),
    customSegment6 VARCHAR(255),
    customSegment7 VARCHAR(255),
    customSegment8 VARCHAR(255),
    customSegment9 VARCHAR(255),
    customSegment10 VARCHAR(255),
    createdPeriodId BIGINT,
    updatedPeriodId BIGINT,
    createdAt DATETIME,
    updatedAt DATETIME,
    CreatedBy VARCHAR(255),
    UpdatedBy VARCHAR(255)
);

create table revenueContractOrderAttributes(
    id BIGINT PRIMARY KEY,
    revenueContractId BIGINT,
    CustomField1 VARCHAR(255),
    CustomField2 VARCHAR(255),
    CustomField3 VARCHAR(255),
    CustomField4 VARCHAR(255),
    CustomField5 VARCHAR(255),
    CustomField6 VARCHAR(255),
    CustomField7 VARCHAR(255),
    CustomField8 VARCHAR(255),
    CustomField9 VARCHAR(255),
    CustomField10 VARCHAR(255),
    CustomField11 VARCHAR(255),
    CustomField12 VARCHAR(255),
    CustomField13 VARCHAR(255),
    CustomField14 VARCHAR(255),
    CustomField15 VARCHAR(255),
    CustomField16 VARCHAR(255),
    CustomField17 VARCHAR(255),
    CustomField18 VARCHAR(255),
    CustomField19 VARCHAR(255),
    CustomField20 VARCHAR(255),
    CustomField21 VARCHAR(255),
    CustomField22 VARCHAR(255),
    CustomField23 VARCHAR(255),
    CustomField24 VARCHAR(255),
    CustomField25 VARCHAR(255),
    CustomField26 VARCHAR(255),
    CustomField27 VARCHAR(255),
    CustomField28 VARCHAR(255),
    CustomField29 VARCHAR(255),
    CustomField30 VARCHAR(255),
    CustomField31 VARCHAR(255),
    CustomField32 VARCHAR(255),
    CustomField33 VARCHAR(255),
    CustomField34 VARCHAR(255),
    CustomField35 VARCHAR(255),
    CustomField36 VARCHAR(255),
    CustomField37 VARCHAR(255),
    CustomField38 VARCHAR(255),
    CustomField39 VARCHAR(255),
    CustomField40 VARCHAR(255),
    CustomField41 VARCHAR(255),
    CustomField42 VARCHAR(255),
    CustomField43 VARCHAR(255),
    CustomField44 VARCHAR(255),
    CustomField45 VARCHAR(255),
    CustomField46 VARCHAR(255),
    CustomField47 VARCHAR(255),
    CustomField48 VARCHAR(255),
    CustomField49 VARCHAR(255),
    CustomField50 VARCHAR(255), 
    CustomField51 VARCHAR(255),
    CustomField52 VARCHAR(255),
    CustomField53 VARCHAR(255),
    CustomField54 VARCHAR(255),
    CustomField55 VARCHAR(255),
    CustomField56 VARCHAR(255),
    CustomField57 VARCHAR(255),
    CustomField58 VARCHAR(255),
    CustomField59 VARCHAR(255),
    CustomField60 VARCHAR(255),
    CustomField61 VARCHAR(255),
    CustomField62 VARCHAR(255),
    CustomField63 VARCHAR(255),
    CustomField64 VARCHAR(255),
    CustomField65 VARCHAR(255),
    CustomField66 VARCHAR(255),
    CustomField67 VARCHAR(255),
    CustomField68 VARCHAR(255),
    CustomField69 VARCHAR(255),
    CustomField70 VARCHAR(255),
    CustomNumber1 DECIMAL(65, 27),
    CustomNumber2 DECIMAL(65, 27),
    CustomNumber3 DECIMAL(65, 27),
    CustomNumber4 DECIMAL(65, 27),
    CustomNumber5 DECIMAL(65, 27),
    CustomNumber6 DECIMAL(65, 27),
    CustomNumber7 DECIMAL(65, 27),
    CustomNumber8 DECIMAL(65, 27),
    CustomNumber9 DECIMAL(65, 27),
    CustomNumber10 DECIMAL(65, 27),
    CustomDate1 DATE,
    CustomDate2 DATE,
    CustomDate3 DATE,
    CustomDate4 DATE,
    CustomDate5 DATE,
    CustomDate6 DATE,
    CustomDate7 DATE, 
    CustomDate8 DATE,
    CustomDate9 DATE,
    CustomDate10 DATE,
    createdPeriodId BIGINT,
    updatedPeriodId BIGINT,
    createdAt DATETIME,
    updatedAt DATETIME,
    CreatedBy VARCHAR(255),
    UpdatedBy VARCHAR(255)
);

create table revenueContractBillingDetails(
    id BIGINT PRIMARY KEY, 
    revenueContractOrderDetailsId BIGINT,
    transactionType VARCHAR(255),
    revenueContractId BIGINT,
    InvoiceId BIGINT,
    InvoiceNumber VARCHAR(255),
    InvoiceDate DATE,
    SellPrice DECIMAL(65, 27),
    ListPrice DECIMAL(65, 27), 
    UnitSellPrice DECIMAL(65, 27),
    UnitListPrice DECIMAL(65, 27),
    transactionCurrency VARCHAR(255),
    FunctionalCurrency VARCHAR(255),
    exchangeRate DECIMAL(65, 27),
    globalexchangeRate DECIMAL(65, 27),
    exchangeRateDate DATE,
    customerNumber VARCHAR(255),
    customerName VARCHAR(255),
    itemNumber VARCHAR(255),
    DeferAmount DECIMAL(65, 27),
    RecognizeAmount DECIMAL(65, 27),
    referenceDocoumentId BIGINT,
    isCancelled BOOLEAN,
    BundleParentId VARCHAR(255),
    BundleConfigurationId BIGINT);

create table revenueContractBillingAccountDetails(
    id BIGINT PRIMARY KEY,
    revenueContractId BIGINT,
    revenueContractOrderDetailsId BIGINT,
    DeferSegment1 VARCHAR(255),
    DeferSegment2 VARCHAR(255),
    DeferSegment3 VARCHAR(255),
    DeferSegment4 VARCHAR(255),
    DeferSegment5 VARCHAR(255),
    DeferSegment6 VARCHAR(255),
    DeferSegment7 VARCHAR(255),
    DeferSegment8 VARCHAR(255),
    DeferSegment9 VARCHAR(255),
    DeferSegment10 VARCHAR(255),
    RevenueSegment1 VARCHAR(255),
    RevenueSegment2 VARCHAR(255),
    RevenueSegment3 VARCHAR(255),
    RevenueSegment4 VARCHAR(255),
    RevenueSegment5 VARCHAR(255),
    RevenueSegment6 VARCHAR(255),
    RevenueSegment7 VARCHAR(255),
    RevenueSegment8 VARCHAR(255),
    RevenueSegment9 VARCHAR(255),
    RevenueSegment10 VARCHAR(255),
    customSegment1 VARCHAR(255),
    customSegment2 VARCHAR(255),
    customSegment3 VARCHAR(255),
    customSegment4 VARCHAR(255),
    customSegment5 VARCHAR(255),
    customSegment6 VARCHAR(255),
    customSegment7 VARCHAR(255),
    customSegment8 VARCHAR(255),
    customSegment9 VARCHAR(255),
    customSegment10 VARCHAR(255),
    createdPeriodId BIGINT,
    updatedPeriodId BIGINT,
    createdAt DATETIME,
    updatedAt DATETIME,
    CreatedBy VARCHAR(255),
    UpdatedBy VARCHAR(255)
);

create table JournalAccountsSetup(
    id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    SegmentPosition1 VARCHAR(255),
    SegmentPosition2 VARCHAR(255),
    SegmentPosition3 VARCHAR(255),
    SegmentPosition4 VARCHAR(255),
    SegmentPosition5 VARCHAR(255),
    SegmentPosition6 VARCHAR(255),
    SegmentPosition7 VARCHAR(255),
    SegmentPosition8 VARCHAR(255),
    SegmentPosition9 VARCHAR(255),
    SegmentPosition10 VARCHAR(255),
    isActive BOOLEAN,
    createdAt DATETIME,
    updatedAt DATETIME); 

 create table RevenueJournalEntries(
    id BIGINT PRIMARY KEY,
    revenueContractId BIGINT,
    accountPeriodId BIGINT,
    JournalAccountPeriodId BIGINT,
    DebitAccountName VARCHAR(255),
    CreditAccountName VARCHAR(255),
    Amount DECIMAL(65, 27),
    Currency VARCHAR(255),
    functionalCurrency VARCHAR(255),
    exchangeRate DECIMAL(65, 27),
    globalexchangeRate DECIMAL(65, 27),
    exchangeRateDate DATE,
    debitAccount1 VARCHAR(255),
    debitAccount2 VARCHAR(255),
    debitAccount3 VARCHAR(255),
    debitAccount4 VARCHAR(255),
    debitAccount5 VARCHAR(255),
    debitAccount6 VARCHAR(255),
    debitAccount7 VARCHAR(255),
    debitAccount8 VARCHAR(255),
    debitAccount9 VARCHAR(255),
    debitAccount10 VARCHAR(255),
    creditAccount1 VARCHAR(255),
    creditAccount2 VARCHAR(255),
    creditAccount3 VARCHAR(255),
    creditAccount4 VARCHAR(255),
    creditAccount5 VARCHAR(255),
    creditAccount6 VARCHAR(255),
    creditAccount7 VARCHAR(255),
    creditAccount8 VARCHAR(255),
    creditAccount9 VARCHAR(255),
    creditAccount10 VARCHAR(255),
    CreatedAt DATETIME,
    UpdatedAt DATETIME,
    CreatedBy VARCHAR(255),
    UpdatedBy VARCHAR(255),
    createdPeriodId BIGINT,
    updatedPeriodId BIGINT,
    IsPosted BOOLEAN,
    IsUnbilledAccount BOOLEAN,
    IsInitialEntry BOOLEAN,
    isUnbilledReversal BOOLEAN,
    reversalFlag VARCHAR(1),
    customField1 VARCHAR(255),
    customField2 VARCHAR(255),
    customField3 VARCHAR(255),
    customField4 VARCHAR(255),
    customField5 VARCHAR(255),
    customField6 VARCHAR(255),
    customField7 VARCHAR(255),
    customField8 VARCHAR(255),
    customField9 VARCHAR(255),
    customField10 VARCHAR(255)
 );

 create table AllocationJournalEntries( 
    id BIGINT PRIMARY KEY,
    revenueContractId BIGINT,
    accountPeriodId BIGINT,
    JournalAccountPeriodId BIGINT,
    DebitAccountName VARCHAR(255),
    CreditAccountName VARCHAR(255),
    Amount DECIMAL(65, 27),
    Currency VARCHAR(255),
    functionalCurrency VARCHAR(255),
    exchangeRate DECIMAL(65, 27),
    globalexchangeRate DECIMAL(65, 27),
    exchangeRateDate DATE,
    debitAccount1 VARCHAR(255),
    debitAccount2 VARCHAR(255),
    debitAccount3 VARCHAR(255),
    debitAccount4 VARCHAR(255),
    debitAccount5 VARCHAR(255),
    debitAccount6 VARCHAR(255),
    debitAccount7 VARCHAR(255),
    debitAccount8 VARCHAR(255),
    debitAccount9 VARCHAR(255),
    debitAccount10 VARCHAR(255),
    creditAccount1 VARCHAR(255),
    creditAccount2 VARCHAR(255),
    creditAccount3 VARCHAR(255),
    creditAccount4 VARCHAR(255),
    creditAccount5 VARCHAR(255),
    creditAccount6 VARCHAR(255),
    creditAccount7 VARCHAR(255),
    creditAccount8 VARCHAR(255),
    creditAccount9 VARCHAR(255),
    creditAccount10 VARCHAR(255),
    CreatedAt DATETIME,
    UpdatedAt DATETIME,
    CreatedBy VARCHAR(255),
    UpdatedBy VARCHAR(255),
    createdPeriodId BIGINT,
    updatedPeriodId BIGINT,
    IsPosted BOOLEAN,
    IsUnbilledAccount BOOLEAN,
    IsInitialEntry BOOLEAN,
    isUnbilledReversal BOOLEAN,
    reversalFlag VARCHAR(1),
    customField1 VARCHAR(255),
    customField2 VARCHAR(255),
    customField3 VARCHAR(255),
    customField4 VARCHAR(255),
    customField5 VARCHAR(255),
    customField6 VARCHAR(255),
    customField7 VARCHAR(255),
    customField8 VARCHAR(255),
    customField9 VARCHAR(255),
    customField10 VARCHAR(255)
    );


create table RevRecStage(
    id BIGINT PRIMARY KEY,
    transactionType VARCHAR(255),
    processsedFlag VARCHAR(1),
    ErrorMessage VARCHAR(255),
    revenueContractId BIGINT,
    RevenueContractGroupValue VARCHAR(255),
    BatchId BIGINT,
    salesOrderId VARCHAR(255),
    salesOrderNumber VARCHAR(255),
    salesOrderDate DATE,
    InvoiceId VARCHAR(255),
    InvoiceNumber VARCHAR(255),
    InvoiceDate DATE,
    OriginalInvoiceId VARCHAR(255),
    OriginalSalesOrderId VARCHAR(255),
    SellPrice DECIMAL(65, 27),
    ListPrice DECIMAL(65, 27), 
    UnitSellPrice DECIMAL(65, 27),
    UnitListPrice DECIMAL(65, 27),
    transactionCurrency VARCHAR(255),
    FunctionalCurrency VARCHAR(255),
    exchangeRate DECIMAL(65, 27),
    globalexchangeRate DECIMAL(65, 27),
    exchangeRateDate DATE,
    customerNumber VARCHAR(255),
    customerName VARCHAR(255),
    itemNumber VARCHAR(255),
    BundleConfigurationId  BIGINT,
    OrderQuantity  DECIMAL(65, 27),
    InvoiceQuantity DECIMAL(65, 27),
    ReturnQuantity DECIMAL(65, 27),
    RevenueStartDate DATE,
    RevenueEndDate DATE,
    Duration BIGINT,
    Term NUMERIC(18, 2),
    BookId BIGINT,
    OrganizationId BIGINT,
    DiscountAmount DECIMAL(65, 27),
    DiscountPercentage DECIMAL(65, 27), 
    bundleParentId BIGINT,
    companyCode VARCHAR(255),
    IsCancelOrder BOOLEAN,
    IsReturnOrder BOOLEAN,   
    Comments VARCHAR(255),
    CreatedBy VARCHAR(255),
    CreatedAt DATETIME,
    UpdatedBy VARCHAR(255),
    UpdatedAt DATETIME, 
    ProductCategory VARCHAR(255),
    ProductClass VARCHAR(255),
    ProductFamily VARCHAR(255),
    ProductLine VARCHAR(255),
    BusinessUnit VARCHAR(255),
    ContractModificationDate DATE,
    SubscriptionId BIGINT,
    SubscriptionName VARCHAR(255),
    SubscriptionVersion BIGINT,
    SubscriptionStartDate DATE,
    SubscriptionEndDate DATE,
    DeferSegment1 VARCHAR(255),
    DeferSegment2 VARCHAR(255),
    DeferSegment3 VARCHAR(255),
    DeferSegment4 VARCHAR(255),
    DeferSegment5 VARCHAR(255),
    DeferSegment6 VARCHAR(255),
    DeferSegment7 VARCHAR(255),
    DeferSegment8 VARCHAR(255),
    DeferSegment9 VARCHAR(255),
    DeferSegment10 VARCHAR(255),
    RevenueSegment1 VARCHAR(255),
    RevenueSegment2 VARCHAR(255),
    RevenueSegment3 VARCHAR(255),
    RevenueSegment4 VARCHAR(255),
    RevenueSegment5 VARCHAR(255),
    RevenueSegment6 VARCHAR(255),
    RevenueSegment7 VARCHAR(255),
    RevenueSegment8 VARCHAR(255),
    RevenueSegment9 VARCHAR(255),
    RevenueSegment10 VARCHAR(255),
    customSegment1 VARCHAR(255),
    customSegment2 VARCHAR(255),
    customSegment3 VARCHAR(255),
    customSegment4 VARCHAR(255),
    customSegment5 VARCHAR(255),
    customSegment6 VARCHAR(255),
    customSegment7 VARCHAR(255),
    customSegment8 VARCHAR(255),
    customSegment9 VARCHAR(255),
    customSegment10 VARCHAR(255),
    CustomField1 VARCHAR(255),
    CustomField2 VARCHAR(255),
    CustomField3 VARCHAR(255),
    CustomField4 VARCHAR(255),
    CustomField5 VARCHAR(255),
    CustomField6 VARCHAR(255),
    CustomField7 VARCHAR(255),
    CustomField8 VARCHAR(255),
    CustomField9 VARCHAR(255),
    CustomField10 VARCHAR(255),
    CustomField11 VARCHAR(255),
    CustomField12 VARCHAR(255),
    CustomField13 VARCHAR(255),
    CustomField14 VARCHAR(255),
    CustomField15 VARCHAR(255),
    CustomField16 VARCHAR(255),
    CustomField17 VARCHAR(255),
    CustomField18 VARCHAR(255),
    CustomField19 VARCHAR(255),
    CustomField20 VARCHAR(255),
    CustomField21 VARCHAR(255),
    CustomField22 VARCHAR(255),
    CustomField23 VARCHAR(255),
    CustomField24 VARCHAR(255),
    CustomField25 VARCHAR(255),
    CustomField26 VARCHAR(255),
    CustomField27 VARCHAR(255),
    CustomField28 VARCHAR(255),
    CustomField29 VARCHAR(255),
    CustomField30 VARCHAR(255),
    CustomField31 VARCHAR(255),
    CustomField32 VARCHAR(255),
    CustomField33 VARCHAR(255),
    CustomField34 VARCHAR(255),
    CustomField35 VARCHAR(255),
    CustomField36 VARCHAR(255),
    CustomField37 VARCHAR(255),
    CustomField38 VARCHAR(255),
    CustomField39 VARCHAR(255),
    CustomField40 VARCHAR(255),
    CustomField41 VARCHAR(255),
    CustomField42 VARCHAR(255),
    CustomField43 VARCHAR(255),
    CustomField44 VARCHAR(255),
    CustomField45 VARCHAR(255),
    CustomField46 VARCHAR(255),
    CustomField47 VARCHAR(255),
    CustomField48 VARCHAR(255),
    CustomField49 VARCHAR(255),
    CustomField50 VARCHAR(255), 
    CustomField51 VARCHAR(255),
    CustomField52 VARCHAR(255),
    CustomField53 VARCHAR(255),
    CustomField54 VARCHAR(255),
    CustomField55 VARCHAR(255),
    CustomField56 VARCHAR(255),
    CustomField57 VARCHAR(255),
    CustomField58 VARCHAR(255),
    CustomField59 VARCHAR(255),
    CustomField60 VARCHAR(255),
    CustomField61 VARCHAR(255),
    CustomField62 VARCHAR(255),
    CustomField63 VARCHAR(255),
    CustomField64 VARCHAR(255),
    CustomField65 VARCHAR(255),
    CustomField66 VARCHAR(255),
    CustomField67 VARCHAR(255),
    CustomField68 VARCHAR(255),
    CustomField69 VARCHAR(255),
    CustomField70 VARCHAR(255),
    CustomNumber1 DECIMAL(65, 27),
    CustomNumber2 DECIMAL(65, 27),
    CustomNumber3 DECIMAL(65, 27),
    CustomNumber4 DECIMAL(65, 27),
    CustomNumber5 DECIMAL(65, 27),
    CustomNumber6 DECIMAL(65, 27),
    CustomNumber7 DECIMAL(65, 27),
    CustomNumber8 DECIMAL(65, 27),
    CustomNumber9 DECIMAL(65, 27),
    CustomNumber10 DECIMAL(65, 27),
    CustomDate1 DATE,
    CustomDate2 DATE,
    CustomDate3 DATE,
    CustomDate4 DATE,
    CustomDate5 DATE,
    CustomDate6 DATE,
    CustomDate7 DATE, 
    CustomDate8 DATE,
    CustomDate9 DATE,
    CustomDate10 DATE,
    createdPeriodId BIGINT,
    updatedPeriodId BIGINT
);


create table RevRecStageHistory(
    id BIGINT PRIMARY KEY,
    transactionType VARCHAR(255),
    processsedFlag VARCHAR(1),
    ErrorMessage VARCHAR(255),
    revenueContractId BIGINT,
    RevenueContractGroupValue VARCHAR(255),
    BatchId BIGINT,
    salesOrderId VARCHAR(255),
    salesOrderNumber VARCHAR(255),
    salesOrderDate DATE,
    InvoiceId VARCHAR(255),
    InvoiceNumber VARCHAR(255),
    InvoiceDate DATE,
    OriginalInvoiceId VARCHAR(255),
    OriginalSalesOrderId VARCHAR(255),
    SellPrice DECIMAL(65, 27),
    ListPrice DECIMAL(65, 27), 
    UnitSellPrice DECIMAL(65, 27),
    UnitListPrice DECIMAL(65, 27),
    transactionCurrency VARCHAR(255),
    FunctionalCurrency VARCHAR(255),
    exchangeRate DECIMAL(65, 27),
    globalexchangeRate DECIMAL(65, 27),
    exchangeRateDate DATE,
    customerNumber VARCHAR(255),
    customerName VARCHAR(255),
    itemNumber VARCHAR(255),
    BundleConfigurationId  BIGINT,
    OrderQuantity  DECIMAL(65, 27),
    InvoiceQuantity DECIMAL(65, 27),
    ReturnQuantity DECIMAL(65, 27),
    RevenueStartDate DATE,
    RevenueEndDate DATE,
    Duration BIGINT,
    Term NUMERIC(18, 2),
    BookId BIGINT,
    OrganizationId BIGINT,
    DiscountAmount DECIMAL(65, 27),
    DiscountPercentage DECIMAL(65, 27), 
    bundleParentId BIGINT,
    companyCode VARCHAR(255),
    IsCancelOrder BOOLEAN,
    IsReturnOrder BOOLEAN,   
    Comments VARCHAR(255),
    CreatedBy VARCHAR(255),
    CreatedAt DATETIME,
    UpdatedBy VARCHAR(255),
    UpdatedAt DATETIME, 
    ProductCategory VARCHAR(255),
    ProductClass VARCHAR(255),
    ProductFamily VARCHAR(255),
    ProductLine VARCHAR(255),
    BusinessUnit VARCHAR(255),
    ContractModificationDate DATE,
    SubscriptionId BIGINT,
    SubscriptionName VARCHAR(255),
    SubscriptionVersion BIGINT,
    SubscriptionStartDate DATE,
    SubscriptionEndDate DATE,
    DeferSegment1 VARCHAR(255),
    DeferSegment2 VARCHAR(255),
    DeferSegment3 VARCHAR(255),
    DeferSegment4 VARCHAR(255),
    DeferSegment5 VARCHAR(255),
    DeferSegment6 VARCHAR(255),
    DeferSegment7 VARCHAR(255),
    DeferSegment8 VARCHAR(255),
    DeferSegment9 VARCHAR(255),
    DeferSegment10 VARCHAR(255),
    RevenueSegment1 VARCHAR(255),
    RevenueSegment2 VARCHAR(255),
    RevenueSegment3 VARCHAR(255),
    RevenueSegment4 VARCHAR(255),
    RevenueSegment5 VARCHAR(255),
    RevenueSegment6 VARCHAR(255),
    RevenueSegment7 VARCHAR(255),
    RevenueSegment8 VARCHAR(255),
    RevenueSegment9 VARCHAR(255),
    RevenueSegment10 VARCHAR(255),
    customSegment1 VARCHAR(255),
    customSegment2 VARCHAR(255),
    customSegment3 VARCHAR(255),
    customSegment4 VARCHAR(255),
    customSegment5 VARCHAR(255),
    customSegment6 VARCHAR(255),
    customSegment7 VARCHAR(255),
    customSegment8 VARCHAR(255),
    customSegment9 VARCHAR(255),
    customSegment10 VARCHAR(255),
    CustomField1 VARCHAR(255),
    CustomField2 VARCHAR(255),
    CustomField3 VARCHAR(255),
    CustomField4 VARCHAR(255),
    CustomField5 VARCHAR(255),
    CustomField6 VARCHAR(255),
    CustomField7 VARCHAR(255),
    CustomField8 VARCHAR(255),
    CustomField9 VARCHAR(255),
    CustomField10 VARCHAR(255),
    CustomField11 VARCHAR(255),
    CustomField12 VARCHAR(255),
    CustomField13 VARCHAR(255),
    CustomField14 VARCHAR(255),
    CustomField15 VARCHAR(255),
    CustomField16 VARCHAR(255),
    CustomField17 VARCHAR(255),
    CustomField18 VARCHAR(255),
    CustomField19 VARCHAR(255),
    CustomField20 VARCHAR(255),
    CustomField21 VARCHAR(255),
    CustomField22 VARCHAR(255),
    CustomField23 VARCHAR(255),
    CustomField24 VARCHAR(255),
    CustomField25 VARCHAR(255),
    CustomField26 VARCHAR(255),
    CustomField27 VARCHAR(255),
    CustomField28 VARCHAR(255),
    CustomField29 VARCHAR(255),
    CustomField30 VARCHAR(255),
    CustomField31 VARCHAR(255),
    CustomField32 VARCHAR(255),
    CustomField33 VARCHAR(255),
    CustomField34 VARCHAR(255),
    CustomField35 VARCHAR(255),
    CustomField36 VARCHAR(255),
    CustomField37 VARCHAR(255),
    CustomField38 VARCHAR(255),
    CustomField39 VARCHAR(255),
    CustomField40 VARCHAR(255),
    CustomField41 VARCHAR(255),
    CustomField42 VARCHAR(255),
    CustomField43 VARCHAR(255),
    CustomField44 VARCHAR(255),
    CustomField45 VARCHAR(255),
    CustomField46 VARCHAR(255),
    CustomField47 VARCHAR(255),
    CustomField48 VARCHAR(255),
    CustomField49 VARCHAR(255),
    CustomField50 VARCHAR(255), 
    CustomField51 VARCHAR(255),
    CustomField52 VARCHAR(255),
    CustomField53 VARCHAR(255),
    CustomField54 VARCHAR(255),
    CustomField55 VARCHAR(255),
    CustomField56 VARCHAR(255),
    CustomField57 VARCHAR(255),
    CustomField58 VARCHAR(255),
    CustomField59 VARCHAR(255),
    CustomField60 VARCHAR(255),
    CustomField61 VARCHAR(255),
    CustomField62 VARCHAR(255),
    CustomField63 VARCHAR(255),
    CustomField64 VARCHAR(255),
    CustomField65 VARCHAR(255),
    CustomField66 VARCHAR(255),
    CustomField67 VARCHAR(255),
    CustomField68 VARCHAR(255),
    CustomField69 VARCHAR(255),
    CustomField70 VARCHAR(255),
    CustomNumber1 DECIMAL(65, 27),
    CustomNumber2 DECIMAL(65, 27),
    CustomNumber3 DECIMAL(65, 27),
    CustomNumber4 DECIMAL(65, 27),
    CustomNumber5 DECIMAL(65, 27),
    CustomNumber6 DECIMAL(65, 27),
    CustomNumber7 DECIMAL(65, 27),
    CustomNumber8 DECIMAL(65, 27),
    CustomNumber9 DECIMAL(65, 27),
    CustomNumber10 DECIMAL(65, 27),
    CustomDate1 DATE,
    CustomDate2 DATE,
    CustomDate3 DATE,
    CustomDate4 DATE,
    CustomDate5 DATE,
    CustomDate6 DATE,
    CustomDate7 DATE, 
    CustomDate8 DATE,
    CustomDate9 DATE,
    CustomDate10 DATE,
    createdPeriodId BIGINT,
    updatedPeriodId BIGINT
);

create table contractModificationHeader(
    id INT PRIMARY KEY,
    InitialContractModificationDuration VARCHAR(255),
    RevisionContractModificationDuration VARCHAR(255),
    InitialContractModificationSspDateMethod VARCHAR(255),
    RevisionContractModificationSspDateMethod VARCHAR(255),
    createdPeriodId INT,
    updatedPeriodId INT,
    createdAt DATETIME,
    updatedAt DATETIME,
    createdBy VARCHAR(255),
    updatedBy VARCHAR(255)
);

create table contractModificationDetails(
    id INT PRIMARY KEY,
    RuleName VARCHAR(255),
    RuleTreatmentForDistinctPob VARCHAR(255),
    RuleTreatmentForNonDistinctPob VARCHAR(255),
    ruleCategory VARCHAR(255),
    IsActive BOOLEAN,
    createdPeriodId INT,
    updatedPeriodId INT,
    createdAt DATETIME,
    updatedAt DATETIME,
    createdBy VARCHAR(255));

create table RevenueContractModificationDetails(
    id BIGINT PRIMARY KEY,
    revenueContractId BIGINT,
    revenueContractLineId BIGINT,
    contractModificationRuleName VARCHAR(255),
    contractModificationDate DATE,
    contractModificationRuleTreatment VARCHAR(255),
    createdPeriodId BIGINT, 
    createdAt DATETIME,
    updatedAt DATETIME,
    createdBy VARCHAR(255),
    updatedBy VARCHAR(255)
);

